// <auto-generated />
using System;
using CapstoneProject.Infrastructure.Database.AppDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CapstoneProject.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CapstoneProject.Domain.Entities.Council", b =>
                {
                    b.Property<int>("CouncilId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CouncilId"));

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CouncilId")
                        .HasName("PK__Councils__1BBAA5C1277B516D");

                    b.ToTable("Councils");
                });

            modelBuilder.Entity("CapstoneProject.Domain.Entities.CouncilMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CouncilId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__CouncilM__3214EC07CB79116F");

                    b.HasIndex("CouncilId");

                    b.HasIndex("UserId");

                    b.ToTable("CouncilMembers");
                });

            modelBuilder.Entity("CapstoneProject.Domain.Entities.DefenseSchedule", b =>
                {
                    b.Property<int>("DefenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DefenseId"));

                    b.Property<int?>("CouncilId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("Room")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Scheduled");

                    b.HasKey("DefenseId")
                        .HasName("PK__DefenseS__63CF1C44D5B9F05F");

                    b.HasIndex("CouncilId");

                    b.HasIndex("GroupId");

                    b.ToTable("DefenseSchedules");
                });

            modelBuilder.Entity("CapstoneProject.Domain.Entities.DefenseScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CouncilMemberId")
                        .HasColumnType("int");

                    b.Property<int?>("DefenseId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal?>("Score")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("Id")
                        .HasName("PK__DefenseS__3214EC074DC0D66C");

                    b.HasIndex("CouncilMemberId");

                    b.HasIndex("DefenseId");

                    b.ToTable("DefenseScores");
                });

            modelBuilder.Entity("CapstoneProject.Domain.Entities.FinalGrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AverageScore")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("GradeLetter")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__FinalGra__3214EC07BC0A6230");

                    b.HasIndex(new[] { "GroupId" }, "UQ__FinalGra__149AF36B5AEB251B")
                        .IsUnique()
                        .HasFilter("[GroupId] IS NOT NULL");

                    b.ToTable("FinalGrades");
                });

            modelBuilder.Entity("CapstoneProject.Domain.Entities.GradeComplaint", b =>
                {
                    b.Property<int>("ComplaintId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComplaintId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResolutionNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ResolvedBy")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.Property<int?>("SubmittedBy")
                        .HasColumnType("int");

                    b.HasKey("ComplaintId")
                        .HasName("PK__GradeCom__740D898FD9546DC6");

                    b.HasIndex("GroupId");

                    b.HasIndex("ResolvedBy");

                    b.HasIndex("SubmittedBy");

                    b.ToTable("GradeComplaints");
                });

            modelBuilder.Entity("CapstoneProject.Domain.Entities.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("LeaderId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Forming");

                    b.HasKey("GroupId")
                        .HasName("PK__Groups__149AF36ADC67C265");

                    b.HasIndex("LeaderId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("CapstoneProject.Domain.Entities.GroupInvitation", b =>
                {
                    b.Property<int>("InvitationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvitationId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<int?>("ReceiverId")
                        .HasColumnType("int");

                    b.Property<int?>("SenderId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.HasKey("InvitationId")
                        .HasName("PK__GroupInv__033C8DCF43D4832F");

                    b.HasIndex("GroupId");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("GroupInvitations");
                });

            modelBuilder.Entity("CapstoneProject.Domain.Entities.GroupMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("RoleInGroup")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Member");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__GroupMem__3214EC078A4895B7");

                    b.HasIndex("GroupId");

                    b.HasIndex(new[] { "UserId" }, "UQ_User_OneGroup")
                        .IsUnique();

                    b.ToTable("GroupMembers");
                });

            modelBuilder.Entity("CapstoneProject.Domain.Entities.LoginHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ipaddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("IPAddress");

                    b.Property<bool?>("IsSuccess")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LoginTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__LoginHis__3214EC070261AB16");

                    b.HasIndex("UserId");

                    b.ToTable("LoginHistories");
                });

            modelBuilder.Entity("CapstoneProject.Domain.Entities.MentorAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<int?>("MentorId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__MentorAs__3214EC077D88805E");

                    b.HasIndex("MentorId");

                    b.HasIndex(new[] { "GroupId" }, "UQ__MentorAs__149AF36B3C559856")
                        .IsUnique()
                        .HasFilter("[GroupId] IS NOT NULL");

                    b.ToTable("MentorAssignments");
                });

            modelBuilder.Entity("CapstoneProject.Domain.Entities.MentorRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<int?>("MentorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RequestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.HasKey("Id")
                        .HasName("PK__MentorRe__3214EC07BCE2BF65");

                    b.HasIndex("GroupId");

                    b.HasIndex("MentorId");

                    b.ToTable("MentorRequests");
                });

            modelBuilder.Entity("CapstoneProject.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Token")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Password__3214EC07B8316D54");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("CapstoneProject.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TokenId"));

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TokenId")
                        .HasName("PK__RefreshT__658FEEEA870856C2");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("CapstoneProject.Domain.Entities.Topic", b =>
                {
                    b.Property<int>("TopicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TopicId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int?>("CurrentVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Draft");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("TopicId")
                        .HasName("PK__Topics__022E0F5DAF8BACA3");

                    b.HasIndex(new[] { "GroupId" }, "UQ__Topics__149AF36BBD8FDC91")
                        .IsUnique()
                        .HasFilter("[GroupId] IS NOT NULL");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("CapstoneProject.Domain.Entities.TopicVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReviewComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReviewedBy")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("TopicId")
                        .HasColumnType("int");

                    b.Property<int?>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__TopicVer__3214EC076FE39582");

                    b.HasIndex("ReviewedBy");

                    b.HasIndex("TopicId");

                    b.ToTable("TopicVersions");
                });

            modelBuilder.Entity("CapstoneProject.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("EmailVerified")
                        .HasColumnType("bit");

                    b.Property<int?>("FailedLoginCount")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("LockUntil")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VerifyToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("VerifyTokenExpire")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D10534693D73B8")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CapstoneProject.Domain.Entities.WeekDefinition", b =>
                {
                    b.Property<int>("WeekId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WeekId"));

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<int?>("WeekNumber")
                        .HasColumnType("int");

                    b.HasKey("WeekId")
                        .HasName("PK__WeekDefi__C814A5C1CCD2D069");

                    b.ToTable("WeekDefinitions");
                });

            modelBuilder.Entity("CapstoneProject.Domain.Entities.WeeklyEvaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsPass")
                        .HasColumnType("bit");

                    b.Property<int?>("MentorId")
                        .HasColumnType("int");

                    b.Property<int?>("ReportId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReviewedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<decimal?>("Score")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("Id")
                        .HasName("PK__WeeklyEv__3214EC07EBCFAFD1");

                    b.HasIndex("MentorId");

                    b.HasIndex("ReportId");

                    b.ToTable("WeeklyEvaluations");
                });

            modelBuilder.Entity("CapstoneProject.Domain.Entities.WeeklyReport", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GithubLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Submitted");

                    b.Property<DateTime?>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int?>("WeekId")
                        .HasColumnType("int");

                    b.HasKey("ReportId")
                        .HasName("PK__WeeklyRe__D5BD480589502696");

                    b.HasIndex("WeekId");

                    b.HasIndex(new[] { "GroupId", "WeekId" }, "UQ_Group_Week")
                        .IsUnique()
                        .HasFilter("[GroupId] IS NOT NULL AND [WeekId] IS NOT NULL");

                    b.ToTable("WeeklyReports");
                });

            modelBuilder.Entity("CapstoneProject.Domain.Entities.CouncilMember", b =>
                {
                    b.HasOne("CapstoneProject.Domain.Entities.Council", "Council")
                        .WithMany("CouncilMembers")
                        .HasForeignKey("CouncilId")
                        .HasConstraintName("FK__CouncilMe__Counc__1CBC4616");

                    b.HasOne("CapstoneProject.Domain.Entities.User", "User")
                        .WithMany("CouncilMembers")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__CouncilMe__UserI__1DB06A4F");

                    b.Navigation("Council");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CapstoneProject.Domain.Entities.DefenseSchedule", b =>
                {
                    b.HasOne("CapstoneProject.Domain.Entities.Council", "Council")
                        .WithMany("DefenseSchedules")
                        .HasForeignKey("CouncilId")
                        .HasConstraintName("FK__DefenseSc__Counc__22751F6C");

                    b.HasOne("CapstoneProject.Domain.Entities.Group", "Group")
                        .WithMany("DefenseSchedules")
                        .HasForeignKey("GroupId")
                        .HasConstraintName("FK__DefenseSc__Group__2180FB33");

                    b.Navigation("Council");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("CapstoneProject.Domain.Entities.DefenseScore", b =>
                {
                    b.HasOne("CapstoneProject.Domain.Entities.CouncilMember", "CouncilMember")
                        .WithMany("DefenseScores")
                        .HasForeignKey("CouncilMemberId")
                        .HasConstraintName("FK__DefenseSc__Counc__2739D489");

                    b.HasOne("CapstoneProject.Domain.Entities.DefenseSchedule", "Defense")
                        .WithMany("DefenseScores")
                        .HasForeignKey("DefenseId")
                        .HasConstraintName("FK__DefenseSc__Defen__2645B050");

                    b.Navigation("CouncilMember");

                    b.Navigation("Defense");
                });

            modelBuilder.Entity("CapstoneProject.Domain.Entities.FinalGrade", b =>
                {
                    b.HasOne("CapstoneProject.Domain.Entities.Group", "Group")
                        .WithOne("FinalGrade")
                        .HasForeignKey("CapstoneProject.Domain.Entities.FinalGrade", "GroupId")
                        .HasConstraintName("FK__FinalGrad__Group__2BFE89A6");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("CapstoneProject.Domain.Entities.GradeComplaint", b =>
                {
                    b.HasOne("CapstoneProject.Domain.Entities.Group", "Group")
                        .WithMany("GradeComplaints")
                        .HasForeignKey("GroupId")
                        .HasConstraintName("FK__GradeComp__Group__30C33EC3");

                    b.HasOne("CapstoneProject.Domain.Entities.User", "ResolvedByNavigation")
                        .WithMany("GradeComplaintResolvedByNavigations")
                        .HasForeignKey("ResolvedBy")
                        .HasConstraintName("FK__GradeComp__Resol__32AB8735");

                    b.HasOne("CapstoneProject.Domain.Entities.User", "SubmittedByNavigation")
                        .WithMany("GradeComplaintSubmittedByNavigations")
                        .HasForeignKey("SubmittedBy")
                        .HasConstraintName("FK__GradeComp__Submi__31B762FC");

                    b.Navigation("Group");

                    b.Navigation("ResolvedByNavigation");

                    b.Navigation("SubmittedByNavigation");
                });

            modelBuilder.Entity("CapstoneProject.Domain.Entities.Group", b =>
                {
                    b.HasOne("CapstoneProject.Domain.Entities.User", "Leader")
                        .WithMany("Groups")
                        .HasForeignKey("LeaderId")
                        .HasConstraintName("FK__Groups__LeaderId__66603565");

                    b.Navigation("Leader");
                });

            modelBuilder.Entity("CapstoneProject.Domain.Entities.GroupInvitation", b =>
                {
                    b.HasOne("CapstoneProject.Domain.Entities.Group", "Group")
                        .WithMany("GroupInvitations")
                        .HasForeignKey("GroupId")
                        .HasConstraintName("FK__GroupInvi__Group__71D1E811");

                    b.HasOne("CapstoneProject.Domain.Entities.User", "Receiver")
                        .WithMany("GroupInvitationReceivers")
                        .HasForeignKey("ReceiverId")
                        .HasConstraintName("FK__GroupInvi__Recei__73BA3083");

                    b.HasOne("CapstoneProject.Domain.Entities.User", "Sender")
                        .WithMany("GroupInvitationSenders")
                        .HasForeignKey("SenderId")
                        .HasConstraintName("FK__GroupInvi__Sende__72C60C4A");

                    b.Navigation("Group");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("CapstoneProject.Domain.Entities.GroupMember", b =>
                {
                    b.HasOne("CapstoneProject.Domain.Entities.Group", "Group")
                        .WithMany("GroupMembers")
                        .HasForeignKey("GroupId")
                        .IsRequired()
                        .HasConstraintName("FK__GroupMemb__Group__6C190EBB");

                    b.HasOne("CapstoneProject.Domain.Entities.User", "User")
                        .WithOne("GroupMember")
                        .HasForeignKey("CapstoneProject.Domain.Entities.GroupMember", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK__GroupMemb__UserI__6D0D32F4");

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CapstoneProject.Domain.Entities.LoginHistory", b =>
                {
                    b.HasOne("CapstoneProject.Domain.Entities.User", "User")
                        .WithMany("LoginHistories")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__LoginHist__UserI__5CD6CB2B");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CapstoneProject.Domain.Entities.MentorAssignment", b =>
                {
                    b.HasOne("CapstoneProject.Domain.Entities.Group", "Group")
                        .WithOne("MentorAssignment")
                        .HasForeignKey("CapstoneProject.Domain.Entities.MentorAssignment", "GroupId")
                        .HasConstraintName("FK__MentorAss__Group__7E37BEF6");

                    b.HasOne("CapstoneProject.Domain.Entities.User", "Mentor")
                        .WithMany("MentorAssignments")
                        .HasForeignKey("MentorId")
                        .HasConstraintName("FK__MentorAss__Mento__7F2BE32F");

                    b.Navigation("Group");

                    b.Navigation("Mentor");
                });

            modelBuilder.Entity("CapstoneProject.Domain.Entities.MentorRequest", b =>
                {
                    b.HasOne("CapstoneProject.Domain.Entities.Group", "Group")
                        .WithMany("MentorRequests")
                        .HasForeignKey("GroupId")
                        .HasConstraintName("FK__MentorReq__Group__787EE5A0");

                    b.HasOne("CapstoneProject.Domain.Entities.User", "Mentor")
                        .WithMany("MentorRequests")
                        .HasForeignKey("MentorId")
                        .HasConstraintName("FK__MentorReq__Mento__797309D9");

                    b.Navigation("Group");

                    b.Navigation("Mentor");
                });

            modelBuilder.Entity("CapstoneProject.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("CapstoneProject.Domain.Entities.User", "User")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__PasswordR__UserI__60A75C0F");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CapstoneProject.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("CapstoneProject.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__RefreshTo__UserI__59063A47");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CapstoneProject.Domain.Entities.Topic", b =>
                {
                    b.HasOne("CapstoneProject.Domain.Entities.Group", "Group")
                        .WithOne("Topic")
                        .HasForeignKey("CapstoneProject.Domain.Entities.Topic", "GroupId")
                        .HasConstraintName("FK__Topics__GroupId__05D8E0BE");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("CapstoneProject.Domain.Entities.TopicVersion", b =>
                {
                    b.HasOne("CapstoneProject.Domain.Entities.User", "ReviewedByNavigation")
                        .WithMany("TopicVersions")
                        .HasForeignKey("ReviewedBy")
                        .HasConstraintName("FK__TopicVers__Revie__0A9D95DB");

                    b.HasOne("CapstoneProject.Domain.Entities.Topic", "Topic")
                        .WithMany("TopicVersions")
                        .HasForeignKey("TopicId")
                        .HasConstraintName("FK__TopicVers__Topic__09A971A2");

                    b.Navigation("ReviewedByNavigation");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("CapstoneProject.Domain.Entities.WeeklyEvaluation", b =>
                {
                    b.HasOne("CapstoneProject.Domain.Entities.User", "Mentor")
                        .WithMany("WeeklyEvaluations")
                        .HasForeignKey("MentorId")
                        .HasConstraintName("FK__WeeklyEva__Mento__17F790F9");

                    b.HasOne("CapstoneProject.Domain.Entities.WeeklyReport", "Report")
                        .WithMany("WeeklyEvaluations")
                        .HasForeignKey("ReportId")
                        .HasConstraintName("FK__WeeklyEva__Repor__17036CC0");

                    b.Navigation("Mentor");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("CapstoneProject.Domain.Entities.WeeklyReport", b =>
                {
                    b.HasOne("CapstoneProject.Domain.Entities.Group", "Group")
                        .WithMany("WeeklyReports")
                        .HasForeignKey("GroupId")
                        .HasConstraintName("FK__WeeklyRep__Group__123EB7A3");

                    b.HasOne("CapstoneProject.Domain.Entities.WeekDefinition", "Week")
                        .WithMany("WeeklyReports")
                        .HasForeignKey("WeekId")
                        .HasConstraintName("FK__WeeklyRep__WeekI__1332DBDC");

                    b.Navigation("Group");

                    b.Navigation("Week");
                });

            modelBuilder.Entity("CapstoneProject.Domain.Entities.Council", b =>
                {
                    b.Navigation("CouncilMembers");

                    b.Navigation("DefenseSchedules");
                });

            modelBuilder.Entity("CapstoneProject.Domain.Entities.CouncilMember", b =>
                {
                    b.Navigation("DefenseScores");
                });

            modelBuilder.Entity("CapstoneProject.Domain.Entities.DefenseSchedule", b =>
                {
                    b.Navigation("DefenseScores");
                });

            modelBuilder.Entity("CapstoneProject.Domain.Entities.Group", b =>
                {
                    b.Navigation("DefenseSchedules");

                    b.Navigation("FinalGrade");

                    b.Navigation("GradeComplaints");

                    b.Navigation("GroupInvitations");

                    b.Navigation("GroupMembers");

                    b.Navigation("MentorAssignment");

                    b.Navigation("MentorRequests");

                    b.Navigation("Topic");

                    b.Navigation("WeeklyReports");
                });

            modelBuilder.Entity("CapstoneProject.Domain.Entities.Topic", b =>
                {
                    b.Navigation("TopicVersions");
                });

            modelBuilder.Entity("CapstoneProject.Domain.Entities.User", b =>
                {
                    b.Navigation("CouncilMembers");

                    b.Navigation("GradeComplaintResolvedByNavigations");

                    b.Navigation("GradeComplaintSubmittedByNavigations");

                    b.Navigation("GroupInvitationReceivers");

                    b.Navigation("GroupInvitationSenders");

                    b.Navigation("GroupMember");

                    b.Navigation("Groups");

                    b.Navigation("LoginHistories");

                    b.Navigation("MentorAssignments");

                    b.Navigation("MentorRequests");

                    b.Navigation("PasswordResetTokens");

                    b.Navigation("RefreshTokens");

                    b.Navigation("TopicVersions");

                    b.Navigation("WeeklyEvaluations");
                });

            modelBuilder.Entity("CapstoneProject.Domain.Entities.WeekDefinition", b =>
                {
                    b.Navigation("WeeklyReports");
                });

            modelBuilder.Entity("CapstoneProject.Domain.Entities.WeeklyReport", b =>
                {
                    b.Navigation("WeeklyEvaluations");
                });
#pragma warning restore 612, 618
        }
    }
}
